-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accumulate is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    agg_result_rowptr_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    agg_result_rowptr_ce0 : OUT STD_LOGIC;
    agg_result_rowptr_we0 : OUT STD_LOGIC;
    agg_result_rowptr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    agg_result_rowptr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    agg_result_colind_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    agg_result_colind_ce0 : OUT STD_LOGIC;
    agg_result_colind_we0 : OUT STD_LOGIC;
    agg_result_colind_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    agg_result_data_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    agg_result_data_V_ce0 : OUT STD_LOGIC;
    agg_result_data_V_we0 : OUT STD_LOGIC;
    agg_result_data_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    csr1_rowptr_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    csr1_rowptr_ce0 : OUT STD_LOGIC;
    csr1_rowptr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    csr1_rowptr_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    csr1_rowptr_ce1 : OUT STD_LOGIC;
    csr1_rowptr_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    csr1_colind_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    csr1_colind_ce0 : OUT STD_LOGIC;
    csr1_colind_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    csr1_data_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    csr1_data_V_ce0 : OUT STD_LOGIC;
    csr1_data_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    csr2_rowptr_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    csr2_rowptr_ce0 : OUT STD_LOGIC;
    csr2_rowptr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    csr2_rowptr_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    csr2_rowptr_ce1 : OUT STD_LOGIC;
    csr2_rowptr_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    csr2_colind_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    csr2_colind_ce0 : OUT STD_LOGIC;
    csr2_colind_q0 : IN STD_LOGIC_VECTOR (8 downto 0);
    csr2_data_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    csr2_data_V_ce0 : OUT STD_LOGIC;
    csr2_data_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of accumulate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_1EE : STD_LOGIC_VECTOR (8 downto 0) := "111101110";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_3_fu_438_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_3_reg_636 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_451_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_reg_646 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal end_idx_1_reg_676 : STD_LOGIC_VECTOR (31 downto 0);
    signal end_idx_2_reg_689 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_76_fu_473_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_76_reg_705 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_75_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_478_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_77_reg_716 : STD_LOGIC_VECTOR (63 downto 0);
    signal z_idx_fu_501_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_reg_727 : STD_LOGIC_VECTOR (31 downto 0);
    signal csr1_colind_load_reg_733 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_78_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_reg_738 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_524_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_84_reg_745 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_83_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal csr1_data_V_addr_gep_fu_172_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal csr2_data_V_addr_gep_fu_180_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_418_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_425_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_82_fu_529_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_82_reg_782 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal indvars_iv_next_fu_541_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_85_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_6_fu_558_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_6_reg_805 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_2_fu_582_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_2_reg_810 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_1_fu_593_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal tmp_91_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_5_fu_610_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_5_reg_833 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_5_fu_627_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal i_reg_308 : STD_LOGIC_VECTOR (8 downto 0);
    signal indvars_iv_reg_319 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_j_2_phi_fu_353_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal j6_reg_329 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_k_2_phi_fu_367_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal k1_reg_339 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_2_reg_349 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_2_reg_363 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_3_reg_377 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_3_reg_388 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_idx_4_reg_398 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_3_reg_408 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_444_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal agg_result_data_V_ad_496_gep_fu_202_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_81_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_87_fu_552_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_86_fu_587_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_93_fu_604_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_92_fu_616_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal extLd8_fu_507_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd_fu_622_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_73_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_74_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_495_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal smax1_fu_488_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_88_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal smax_fu_569_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_89_fu_576_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_91_fu_599_p2 = ap_const_lv1_0))) then 
                i_reg_308 <= i_3_reg_636;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_308 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    indvars_iv_reg_319_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                indvars_iv_reg_319 <= agg_result_rowptr_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                indvars_iv_reg_319 <= indvars_iv_next_fu_541_p2;
            end if; 
        end if;
    end process;

    j6_reg_329_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                j6_reg_329 <= csr1_rowptr_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                j6_reg_329 <= ap_phi_mux_j_2_phi_fu_353_p6;
            end if; 
        end if;
    end process;

    j_2_reg_349_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_2_reg_349 <= j6_reg_329;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_78_reg_738 = ap_const_lv1_1)))) then 
                j_2_reg_349 <= grp_fu_425_p2;
            end if; 
        end if;
    end process;

    j_3_reg_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                j_3_reg_388 <= j_6_reg_805;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_75_fu_467_p2 = ap_const_lv1_0))) then 
                j_3_reg_388 <= j6_reg_329;
            end if; 
        end if;
    end process;

    k1_reg_339_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                k1_reg_339 <= csr2_rowptr_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                k1_reg_339 <= ap_phi_mux_k_2_phi_fu_367_p6;
            end if; 
        end if;
    end process;

    k_2_reg_363_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                k_2_reg_363 <= k1_reg_339;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_78_reg_738 = ap_const_lv1_1)))) then 
                k_2_reg_363 <= grp_fu_418_p2;
            end if; 
        end if;
    end process;

    k_3_reg_408_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                k_3_reg_408 <= k_5_reg_833;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state10) and (tmp_85_fu_547_p2 = ap_const_lv1_0))) then 
                k_3_reg_408 <= k1_reg_339;
            end if; 
        end if;
    end process;

    z_idx_3_reg_377_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                z_idx_3_reg_377 <= z_idx_1_fu_593_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_75_fu_467_p2 = ap_const_lv1_0))) then 
                z_idx_3_reg_377 <= indvars_iv_reg_319;
            end if; 
        end if;
    end process;

    z_idx_4_reg_398_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                z_idx_4_reg_398 <= z_idx_5_fu_627_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state10) and (tmp_85_fu_547_p2 = ap_const_lv1_0))) then 
                z_idx_4_reg_398 <= z_idx_reg_727;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                csr1_colind_load_reg_733 <= csr1_colind_q0;
                tmp_78_reg_738 <= tmp_78_fu_512_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                end_idx_1_reg_676 <= csr1_rowptr_q1;
                end_idx_2_reg_689 <= csr2_rowptr_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_3_reg_636 <= i_3_fu_438_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (tmp_85_fu_547_p2 = ap_const_lv1_1))) then
                j_6_reg_805 <= j_6_fu_558_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_91_fu_599_p2 = ap_const_lv1_1))) then
                k_5_reg_833 <= k_5_fu_610_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_75_fu_467_p2 = ap_const_lv1_1))) then
                tmp_76_reg_705 <= tmp_76_fu_473_p1;
                tmp_77_reg_716 <= tmp_77_fu_478_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                tmp_82_reg_782 <= tmp_82_fu_529_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_78_fu_512_p2 = ap_const_lv1_0))) then
                tmp_84_reg_745 <= tmp_84_fu_524_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_432_p2 = ap_const_lv1_0))) then
                    tmp_s_reg_646(8 downto 0) <= tmp_s_fu_451_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (tmp_85_fu_547_p2 = ap_const_lv1_0))) then
                z_idx_2_reg_810 <= z_idx_2_fu_582_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_75_fu_467_p2 = ap_const_lv1_0))) then
                z_idx_reg_727 <= z_idx_fu_501_p2;
            end if;
        end if;
    end process;
    tmp_s_reg_646(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_fu_432_p2, ap_CS_fsm_state4, tmp_75_fu_467_p2, ap_CS_fsm_state5, tmp_78_fu_512_p2, tmp_83_fu_518_p2, ap_CS_fsm_state10, tmp_85_fu_547_p2, ap_CS_fsm_state12, tmp_91_fu_599_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_432_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_75_fu_467_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_1) and (tmp_78_fu_512_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_0) and (tmp_78_fu_512_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (tmp_85_fu_547_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_91_fu_599_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;

    agg_result_colind_address0_assign_proc : process(ap_CS_fsm_state5, tmp_84_fu_524_p1, tmp_84_reg_745, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13, tmp_81_fu_535_p1, tmp_86_fu_587_p1, tmp_92_fu_616_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            agg_result_colind_address0 <= tmp_92_fu_616_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            agg_result_colind_address0 <= tmp_86_fu_587_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            agg_result_colind_address0 <= tmp_81_fu_535_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            agg_result_colind_address0 <= tmp_84_reg_745(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            agg_result_colind_address0 <= tmp_84_fu_524_p1(18 - 1 downto 0);
        else 
            agg_result_colind_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    agg_result_colind_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            agg_result_colind_ce0 <= ap_const_logic_1;
        else 
            agg_result_colind_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    agg_result_colind_d0_assign_proc : process(csr1_colind_q0, csr1_colind_load_reg_733, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13, extLd8_fu_507_p1, extLd_fu_622_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            agg_result_colind_d0 <= extLd_fu_622_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            agg_result_colind_d0 <= csr1_colind_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            agg_result_colind_d0 <= csr1_colind_load_reg_733;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            agg_result_colind_d0 <= extLd8_fu_507_p1;
        else 
            agg_result_colind_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    agg_result_colind_we0_assign_proc : process(ap_CS_fsm_state5, tmp_78_fu_512_p2, tmp_78_reg_738, tmp_83_fu_518_p2, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_78_reg_738 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_0) and (tmp_78_fu_512_p2 = ap_const_lv1_0)))) then 
            agg_result_colind_we0 <= ap_const_logic_1;
        else 
            agg_result_colind_we0 <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_data_V_ad_496_gep_fu_202_p3 <= tmp_84_reg_745(18 - 1 downto 0);

    agg_result_data_V_address0_assign_proc : process(tmp_84_reg_745, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13, agg_result_data_V_ad_496_gep_fu_202_p3, tmp_81_fu_535_p1, tmp_86_fu_587_p1, tmp_92_fu_616_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            agg_result_data_V_address0 <= tmp_92_fu_616_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            agg_result_data_V_address0 <= tmp_86_fu_587_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            agg_result_data_V_address0 <= tmp_81_fu_535_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            agg_result_data_V_address0 <= agg_result_data_V_ad_496_gep_fu_202_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            agg_result_data_V_address0 <= tmp_84_reg_745(18 - 1 downto 0);
        else 
            agg_result_data_V_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    agg_result_data_V_ce0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            agg_result_data_V_ce0 <= ap_const_logic_1;
        else 
            agg_result_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    agg_result_data_V_d0_assign_proc : process(csr1_data_V_q0, csr2_data_V_q0, ap_CS_fsm_state6, ap_CS_fsm_state7, tmp_82_reg_782, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            agg_result_data_V_d0 <= tmp_82_reg_782;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            agg_result_data_V_d0 <= csr1_data_V_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            agg_result_data_V_d0 <= csr2_data_V_q0;
        else 
            agg_result_data_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    agg_result_data_V_we0_assign_proc : process(tmp_78_reg_738, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_78_reg_738 = ap_const_lv1_1)))) then 
            agg_result_data_V_we0 <= ap_const_logic_1;
        else 
            agg_result_data_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    agg_result_rowptr_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, tmp_s_reg_646, ap_CS_fsm_state12, tmp_fu_444_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            agg_result_rowptr_address0 <= tmp_s_reg_646(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            agg_result_rowptr_address0 <= tmp_fu_444_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            agg_result_rowptr_address0 <= ap_const_lv64_0(9 - 1 downto 0);
        else 
            agg_result_rowptr_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    agg_result_rowptr_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            agg_result_rowptr_ce0 <= ap_const_logic_1;
        else 
            agg_result_rowptr_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    agg_result_rowptr_d0_assign_proc : process(ap_CS_fsm_state1, z_idx_2_reg_810, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            agg_result_rowptr_d0 <= z_idx_2_reg_810;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            agg_result_rowptr_d0 <= ap_const_lv32_0;
        else 
            agg_result_rowptr_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    agg_result_rowptr_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state12, tmp_91_fu_599_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_91_fu_599_p2 = ap_const_lv1_0)))) then 
            agg_result_rowptr_we0 <= ap_const_logic_1;
        else 
            agg_result_rowptr_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_fu_432_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_432_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_j_2_phi_fu_353_p6_assign_proc : process(tmp_78_reg_738, grp_fu_425_p2, ap_CS_fsm_state9, j_2_reg_349)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_78_reg_738 = ap_const_lv1_1))) then 
            ap_phi_mux_j_2_phi_fu_353_p6 <= grp_fu_425_p2;
        else 
            ap_phi_mux_j_2_phi_fu_353_p6 <= j_2_reg_349;
        end if; 
    end process;


    ap_phi_mux_k_2_phi_fu_367_p6_assign_proc : process(tmp_78_reg_738, grp_fu_418_p2, ap_CS_fsm_state9, k_2_reg_363)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_78_reg_738 = ap_const_lv1_1))) then 
            ap_phi_mux_k_2_phi_fu_367_p6 <= grp_fu_418_p2;
        else 
            ap_phi_mux_k_2_phi_fu_367_p6 <= k_2_reg_363;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_432_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_432_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    csr1_colind_address0_assign_proc : process(tmp_76_fu_473_p1, ap_CS_fsm_state4, ap_CS_fsm_state10, tmp_87_fu_552_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            csr1_colind_address0 <= tmp_87_fu_552_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            csr1_colind_address0 <= tmp_76_fu_473_p1(18 - 1 downto 0);
        else 
            csr1_colind_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    csr1_colind_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            csr1_colind_ce0 <= ap_const_logic_1;
        else 
            csr1_colind_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    csr1_data_V_addr_gep_fu_172_p3 <= tmp_76_reg_705(18 - 1 downto 0);

    csr1_data_V_address0_assign_proc : process(tmp_76_reg_705, ap_CS_fsm_state5, tmp_78_fu_512_p2, tmp_83_fu_518_p2, csr1_data_V_addr_gep_fu_172_p3, ap_CS_fsm_state10, tmp_87_fu_552_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            csr1_data_V_address0 <= tmp_87_fu_552_p1(18 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_78_fu_512_p2 = ap_const_lv1_1))) then 
            csr1_data_V_address0 <= csr1_data_V_addr_gep_fu_172_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_1) and (tmp_78_fu_512_p2 = ap_const_lv1_0))) then 
            csr1_data_V_address0 <= tmp_76_reg_705(18 - 1 downto 0);
        else 
            csr1_data_V_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    csr1_data_V_ce0_assign_proc : process(ap_CS_fsm_state5, tmp_78_fu_512_p2, tmp_83_fu_518_p2, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_78_fu_512_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_1) and (tmp_78_fu_512_p2 = ap_const_lv1_0)))) then 
            csr1_data_V_ce0 <= ap_const_logic_1;
        else 
            csr1_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    csr1_rowptr_address0 <= tmp_fu_444_p1(9 - 1 downto 0);
    csr1_rowptr_address1 <= tmp_s_fu_451_p1(9 - 1 downto 0);

    csr1_rowptr_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            csr1_rowptr_ce0 <= ap_const_logic_1;
        else 
            csr1_rowptr_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    csr1_rowptr_ce1_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            csr1_rowptr_ce1 <= ap_const_logic_1;
        else 
            csr1_rowptr_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    csr2_colind_address0_assign_proc : process(ap_CS_fsm_state4, tmp_77_fu_478_p1, ap_CS_fsm_state12, tmp_93_fu_604_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            csr2_colind_address0 <= tmp_93_fu_604_p1(18 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            csr2_colind_address0 <= tmp_77_fu_478_p1(18 - 1 downto 0);
        else 
            csr2_colind_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    csr2_colind_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            csr2_colind_ce0 <= ap_const_logic_1;
        else 
            csr2_colind_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    csr2_data_V_addr_gep_fu_180_p3 <= tmp_77_reg_716(18 - 1 downto 0);

    csr2_data_V_address0_assign_proc : process(tmp_77_reg_716, ap_CS_fsm_state5, tmp_78_fu_512_p2, tmp_83_fu_518_p2, csr2_data_V_addr_gep_fu_180_p3, ap_CS_fsm_state12, tmp_93_fu_604_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            csr2_data_V_address0 <= tmp_93_fu_604_p1(18 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_78_fu_512_p2 = ap_const_lv1_1))) then 
            csr2_data_V_address0 <= csr2_data_V_addr_gep_fu_180_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_0) and (tmp_78_fu_512_p2 = ap_const_lv1_0))) then 
            csr2_data_V_address0 <= tmp_77_reg_716(18 - 1 downto 0);
        else 
            csr2_data_V_address0 <= "XXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    csr2_data_V_ce0_assign_proc : process(ap_CS_fsm_state5, tmp_78_fu_512_p2, tmp_83_fu_518_p2, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_78_fu_512_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_83_fu_518_p2 = ap_const_lv1_0) and (tmp_78_fu_512_p2 = ap_const_lv1_0)))) then 
            csr2_data_V_ce0 <= ap_const_logic_1;
        else 
            csr2_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    csr2_rowptr_address0 <= tmp_fu_444_p1(9 - 1 downto 0);
    csr2_rowptr_address1 <= tmp_s_fu_451_p1(9 - 1 downto 0);

    csr2_rowptr_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            csr2_rowptr_ce0 <= ap_const_logic_1;
        else 
            csr2_rowptr_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    csr2_rowptr_ce1_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            csr2_rowptr_ce1 <= ap_const_logic_1;
        else 
            csr2_rowptr_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_fu_432_p2 <= "1" when (i_reg_308 = ap_const_lv9_1EE) else "0";
    extLd8_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(csr2_colind_q0),32));
    extLd_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(csr2_colind_q0),32));
    grp_fu_418_p2 <= std_logic_vector(signed(k1_reg_339) + signed(ap_const_lv32_1));
    grp_fu_425_p2 <= std_logic_vector(signed(j6_reg_329) + signed(ap_const_lv32_1));
    i_3_fu_438_p2 <= std_logic_vector(unsigned(i_reg_308) + unsigned(ap_const_lv9_1));
    indvars_iv_next_fu_541_p2 <= std_logic_vector(signed(indvars_iv_reg_319) + signed(ap_const_lv32_1));
    j_6_fu_558_p2 <= std_logic_vector(signed(j_3_reg_388) + signed(ap_const_lv32_1));
    k_5_fu_610_p2 <= std_logic_vector(signed(k_3_reg_408) + signed(ap_const_lv32_1));
    smax1_fu_488_p3 <= 
        j6_reg_329 when (tmp_79_fu_483_p2(0) = '1') else 
        end_idx_1_reg_676;
    smax_fu_569_p3 <= 
        k1_reg_339 when (tmp_88_fu_564_p2(0) = '1') else 
        end_idx_2_reg_689;
    tmp_73_fu_457_p2 <= "1" when (signed(j6_reg_329) < signed(end_idx_1_reg_676)) else "0";
    tmp_74_fu_462_p2 <= "1" when (signed(k1_reg_339) < signed(end_idx_2_reg_689)) else "0";
    tmp_75_fu_467_p2 <= (tmp_74_fu_462_p2 and tmp_73_fu_457_p2);
        tmp_76_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(j6_reg_329),64));

        tmp_77_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k1_reg_339),64));

    tmp_78_fu_512_p2 <= "1" when (csr1_colind_q0 = extLd8_fu_507_p1) else "0";
    tmp_79_fu_483_p2 <= "1" when (signed(j6_reg_329) > signed(end_idx_1_reg_676)) else "0";
    tmp_80_fu_495_p2 <= std_logic_vector(signed(indvars_iv_reg_319) - signed(j6_reg_329));
        tmp_81_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(indvars_iv_reg_319),64));

    tmp_82_fu_529_p2 <= std_logic_vector(unsigned(csr2_data_V_q0) + unsigned(csr1_data_V_q0));
    tmp_83_fu_518_p2 <= "1" when (signed(csr1_colind_q0) < signed(extLd8_fu_507_p1)) else "0";
        tmp_84_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(indvars_iv_reg_319),64));

    tmp_85_fu_547_p2 <= "1" when (signed(j_3_reg_388) < signed(end_idx_1_reg_676)) else "0";
        tmp_86_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(z_idx_3_reg_377),64));

        tmp_87_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(j_3_reg_388),64));

    tmp_88_fu_564_p2 <= "1" when (signed(k1_reg_339) > signed(end_idx_2_reg_689)) else "0";
    tmp_89_fu_576_p2 <= std_logic_vector(unsigned(smax_fu_569_p3) - unsigned(k1_reg_339));
    tmp_91_fu_599_p2 <= "1" when (signed(k_3_reg_408) < signed(end_idx_2_reg_689)) else "0";
        tmp_92_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(z_idx_4_reg_398),64));

        tmp_93_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(k_3_reg_408),64));

    tmp_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_308),64));
    tmp_s_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_fu_438_p2),64));
    z_idx_1_fu_593_p2 <= std_logic_vector(signed(z_idx_3_reg_377) + signed(ap_const_lv32_1));
    z_idx_2_fu_582_p2 <= std_logic_vector(unsigned(z_idx_reg_727) + unsigned(tmp_89_fu_576_p2));
    z_idx_5_fu_627_p2 <= std_logic_vector(signed(z_idx_4_reg_398) + signed(ap_const_lv32_1));
    z_idx_fu_501_p2 <= std_logic_vector(unsigned(tmp_80_fu_495_p2) + unsigned(smax1_fu_488_p3));
end behav;
