// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "accumulate.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic accumulate::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic accumulate::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> accumulate::ap_ST_fsm_state1 = "1";
const sc_lv<13> accumulate::ap_ST_fsm_state2 = "10";
const sc_lv<13> accumulate::ap_ST_fsm_state3 = "100";
const sc_lv<13> accumulate::ap_ST_fsm_state4 = "1000";
const sc_lv<13> accumulate::ap_ST_fsm_state5 = "10000";
const sc_lv<13> accumulate::ap_ST_fsm_state6 = "100000";
const sc_lv<13> accumulate::ap_ST_fsm_state7 = "1000000";
const sc_lv<13> accumulate::ap_ST_fsm_state8 = "10000000";
const sc_lv<13> accumulate::ap_ST_fsm_state9 = "100000000";
const sc_lv<13> accumulate::ap_ST_fsm_state10 = "1000000000";
const sc_lv<13> accumulate::ap_ST_fsm_state11 = "10000000000";
const sc_lv<13> accumulate::ap_ST_fsm_state12 = "100000000000";
const sc_lv<13> accumulate::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> accumulate::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> accumulate::ap_const_lv32_1 = "1";
const sc_lv<1> accumulate::ap_const_lv1_0 = "0";
const sc_lv<32> accumulate::ap_const_lv32_2 = "10";
const sc_lv<32> accumulate::ap_const_lv32_3 = "11";
const sc_lv<1> accumulate::ap_const_lv1_1 = "1";
const sc_lv<32> accumulate::ap_const_lv32_4 = "100";
const sc_lv<32> accumulate::ap_const_lv32_5 = "101";
const sc_lv<32> accumulate::ap_const_lv32_6 = "110";
const sc_lv<32> accumulate::ap_const_lv32_7 = "111";
const sc_lv<32> accumulate::ap_const_lv32_8 = "1000";
const sc_lv<32> accumulate::ap_const_lv32_9 = "1001";
const sc_lv<32> accumulate::ap_const_lv32_A = "1010";
const sc_lv<32> accumulate::ap_const_lv32_B = "1011";
const sc_lv<32> accumulate::ap_const_lv32_C = "1100";
const sc_lv<9> accumulate::ap_const_lv9_0 = "000000000";
const sc_lv<64> accumulate::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<9> accumulate::ap_const_lv9_1EE = "111101110";
const sc_lv<9> accumulate::ap_const_lv9_1 = "1";
const bool accumulate::ap_const_boolean_1 = true;

accumulate::accumulate(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_agg_result_colind_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_84_fu_524_p1 );
    sensitive << ( tmp_84_reg_745 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_81_fu_535_p1 );
    sensitive << ( tmp_86_fu_587_p1 );
    sensitive << ( tmp_92_fu_616_p1 );

    SC_METHOD(thread_agg_result_colind_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_agg_result_colind_d0);
    sensitive << ( csr1_colind_q0 );
    sensitive << ( csr1_colind_load_reg_733 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( extLd8_fu_507_p1 );
    sensitive << ( extLd_fu_622_p1 );

    SC_METHOD(thread_agg_result_colind_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( tmp_78_reg_738 );
    sensitive << ( tmp_83_fu_518_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_agg_result_data_V_ad_496_gep_fu_202_p3);
    sensitive << ( tmp_84_reg_745 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_agg_result_data_V_address0);
    sensitive << ( tmp_84_reg_745 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( agg_result_data_V_ad_496_gep_fu_202_p3 );
    sensitive << ( tmp_81_fu_535_p1 );
    sensitive << ( tmp_86_fu_587_p1 );
    sensitive << ( tmp_92_fu_616_p1 );

    SC_METHOD(thread_agg_result_data_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_agg_result_data_V_d0);
    sensitive << ( csr1_data_V_q0 );
    sensitive << ( csr2_data_V_q0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_82_reg_782 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_agg_result_data_V_we0);
    sensitive << ( tmp_78_reg_738 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_agg_result_rowptr_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_reg_646 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_fu_444_p1 );

    SC_METHOD(thread_agg_result_rowptr_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_agg_result_rowptr_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( z_idx_2_reg_810 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_agg_result_rowptr_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_91_fu_599_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_432_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_j_2_phi_fu_353_p6);
    sensitive << ( tmp_78_reg_738 );
    sensitive << ( grp_fu_425_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( j_2_reg_349 );

    SC_METHOD(thread_ap_phi_mux_k_2_phi_fu_367_p6);
    sensitive << ( tmp_78_reg_738 );
    sensitive << ( grp_fu_418_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( k_2_reg_363 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_432_p2 );

    SC_METHOD(thread_csr1_colind_address0);
    sensitive << ( tmp_76_fu_473_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_87_fu_552_p1 );

    SC_METHOD(thread_csr1_colind_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_csr1_data_V_addr_gep_fu_172_p3);
    sensitive << ( tmp_76_reg_705 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );

    SC_METHOD(thread_csr1_data_V_address0);
    sensitive << ( tmp_76_reg_705 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( tmp_83_fu_518_p2 );
    sensitive << ( csr1_data_V_addr_gep_fu_172_p3 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_87_fu_552_p1 );

    SC_METHOD(thread_csr1_data_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( tmp_83_fu_518_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_csr1_rowptr_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_444_p1 );

    SC_METHOD(thread_csr1_rowptr_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_451_p1 );

    SC_METHOD(thread_csr1_rowptr_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_csr1_rowptr_ce1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_csr2_colind_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_77_fu_478_p1 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_93_fu_604_p1 );

    SC_METHOD(thread_csr2_colind_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_csr2_data_V_addr_gep_fu_180_p3);
    sensitive << ( tmp_77_reg_716 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );

    SC_METHOD(thread_csr2_data_V_address0);
    sensitive << ( tmp_77_reg_716 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( tmp_83_fu_518_p2 );
    sensitive << ( csr2_data_V_addr_gep_fu_180_p3 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_93_fu_604_p1 );

    SC_METHOD(thread_csr2_data_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( tmp_83_fu_518_p2 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_csr2_rowptr_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_444_p1 );

    SC_METHOD(thread_csr2_rowptr_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_451_p1 );

    SC_METHOD(thread_csr2_rowptr_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_csr2_rowptr_ce1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_exitcond_fu_432_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_308 );

    SC_METHOD(thread_extLd8_fu_507_p1);
    sensitive << ( csr2_colind_q0 );

    SC_METHOD(thread_extLd_fu_622_p1);
    sensitive << ( csr2_colind_q0 );

    SC_METHOD(thread_grp_fu_418_p2);
    sensitive << ( k1_reg_339 );

    SC_METHOD(thread_grp_fu_425_p2);
    sensitive << ( j6_reg_329 );

    SC_METHOD(thread_i_3_fu_438_p2);
    sensitive << ( i_reg_308 );

    SC_METHOD(thread_indvars_iv_next_fu_541_p2);
    sensitive << ( indvars_iv_reg_319 );

    SC_METHOD(thread_j_6_fu_558_p2);
    sensitive << ( j_3_reg_388 );

    SC_METHOD(thread_k_5_fu_610_p2);
    sensitive << ( k_3_reg_408 );

    SC_METHOD(thread_smax1_fu_488_p3);
    sensitive << ( end_idx_1_reg_676 );
    sensitive << ( j6_reg_329 );
    sensitive << ( tmp_79_fu_483_p2 );

    SC_METHOD(thread_smax_fu_569_p3);
    sensitive << ( end_idx_2_reg_689 );
    sensitive << ( k1_reg_339 );
    sensitive << ( tmp_88_fu_564_p2 );

    SC_METHOD(thread_tmp_73_fu_457_p2);
    sensitive << ( end_idx_1_reg_676 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j6_reg_329 );

    SC_METHOD(thread_tmp_74_fu_462_p2);
    sensitive << ( end_idx_2_reg_689 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k1_reg_339 );

    SC_METHOD(thread_tmp_75_fu_467_p2);
    sensitive << ( tmp_73_fu_457_p2 );
    sensitive << ( tmp_74_fu_462_p2 );

    SC_METHOD(thread_tmp_76_fu_473_p1);
    sensitive << ( j6_reg_329 );

    SC_METHOD(thread_tmp_77_fu_478_p1);
    sensitive << ( k1_reg_339 );

    SC_METHOD(thread_tmp_78_fu_512_p2);
    sensitive << ( csr1_colind_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( extLd8_fu_507_p1 );

    SC_METHOD(thread_tmp_79_fu_483_p2);
    sensitive << ( end_idx_1_reg_676 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_75_fu_467_p2 );
    sensitive << ( j6_reg_329 );

    SC_METHOD(thread_tmp_80_fu_495_p2);
    sensitive << ( indvars_iv_reg_319 );
    sensitive << ( j6_reg_329 );

    SC_METHOD(thread_tmp_81_fu_535_p1);
    sensitive << ( indvars_iv_reg_319 );

    SC_METHOD(thread_tmp_82_fu_529_p2);
    sensitive << ( csr1_data_V_q0 );
    sensitive << ( csr2_data_V_q0 );

    SC_METHOD(thread_tmp_83_fu_518_p2);
    sensitive << ( csr1_colind_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( extLd8_fu_507_p1 );

    SC_METHOD(thread_tmp_84_fu_524_p1);
    sensitive << ( indvars_iv_reg_319 );

    SC_METHOD(thread_tmp_85_fu_547_p2);
    sensitive << ( end_idx_1_reg_676 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( j_3_reg_388 );

    SC_METHOD(thread_tmp_86_fu_587_p1);
    sensitive << ( z_idx_3_reg_377 );

    SC_METHOD(thread_tmp_87_fu_552_p1);
    sensitive << ( j_3_reg_388 );

    SC_METHOD(thread_tmp_88_fu_564_p2);
    sensitive << ( end_idx_2_reg_689 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_85_fu_547_p2 );
    sensitive << ( k1_reg_339 );

    SC_METHOD(thread_tmp_89_fu_576_p2);
    sensitive << ( k1_reg_339 );
    sensitive << ( smax_fu_569_p3 );

    SC_METHOD(thread_tmp_91_fu_599_p2);
    sensitive << ( end_idx_2_reg_689 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( k_3_reg_408 );

    SC_METHOD(thread_tmp_92_fu_616_p1);
    sensitive << ( z_idx_4_reg_398 );

    SC_METHOD(thread_tmp_93_fu_604_p1);
    sensitive << ( k_3_reg_408 );

    SC_METHOD(thread_tmp_fu_444_p1);
    sensitive << ( i_reg_308 );

    SC_METHOD(thread_tmp_s_fu_451_p1);
    sensitive << ( i_3_fu_438_p2 );

    SC_METHOD(thread_z_idx_1_fu_593_p2);
    sensitive << ( z_idx_3_reg_377 );

    SC_METHOD(thread_z_idx_2_fu_582_p2);
    sensitive << ( z_idx_reg_727 );
    sensitive << ( tmp_89_fu_576_p2 );

    SC_METHOD(thread_z_idx_5_fu_627_p2);
    sensitive << ( z_idx_4_reg_398 );

    SC_METHOD(thread_z_idx_fu_501_p2);
    sensitive << ( tmp_80_fu_495_p2 );
    sensitive << ( smax1_fu_488_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_432_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_75_fu_467_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_78_fu_512_p2 );
    sensitive << ( tmp_83_fu_518_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_85_fu_547_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_91_fu_599_p2 );

    ap_CS_fsm = "0000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "accumulate_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, agg_result_rowptr_address0, "(port)agg_result_rowptr_address0");
    sc_trace(mVcdFile, agg_result_rowptr_ce0, "(port)agg_result_rowptr_ce0");
    sc_trace(mVcdFile, agg_result_rowptr_we0, "(port)agg_result_rowptr_we0");
    sc_trace(mVcdFile, agg_result_rowptr_d0, "(port)agg_result_rowptr_d0");
    sc_trace(mVcdFile, agg_result_rowptr_q0, "(port)agg_result_rowptr_q0");
    sc_trace(mVcdFile, agg_result_colind_address0, "(port)agg_result_colind_address0");
    sc_trace(mVcdFile, agg_result_colind_ce0, "(port)agg_result_colind_ce0");
    sc_trace(mVcdFile, agg_result_colind_we0, "(port)agg_result_colind_we0");
    sc_trace(mVcdFile, agg_result_colind_d0, "(port)agg_result_colind_d0");
    sc_trace(mVcdFile, agg_result_data_V_address0, "(port)agg_result_data_V_address0");
    sc_trace(mVcdFile, agg_result_data_V_ce0, "(port)agg_result_data_V_ce0");
    sc_trace(mVcdFile, agg_result_data_V_we0, "(port)agg_result_data_V_we0");
    sc_trace(mVcdFile, agg_result_data_V_d0, "(port)agg_result_data_V_d0");
    sc_trace(mVcdFile, csr1_rowptr_address0, "(port)csr1_rowptr_address0");
    sc_trace(mVcdFile, csr1_rowptr_ce0, "(port)csr1_rowptr_ce0");
    sc_trace(mVcdFile, csr1_rowptr_q0, "(port)csr1_rowptr_q0");
    sc_trace(mVcdFile, csr1_rowptr_address1, "(port)csr1_rowptr_address1");
    sc_trace(mVcdFile, csr1_rowptr_ce1, "(port)csr1_rowptr_ce1");
    sc_trace(mVcdFile, csr1_rowptr_q1, "(port)csr1_rowptr_q1");
    sc_trace(mVcdFile, csr1_colind_address0, "(port)csr1_colind_address0");
    sc_trace(mVcdFile, csr1_colind_ce0, "(port)csr1_colind_ce0");
    sc_trace(mVcdFile, csr1_colind_q0, "(port)csr1_colind_q0");
    sc_trace(mVcdFile, csr1_data_V_address0, "(port)csr1_data_V_address0");
    sc_trace(mVcdFile, csr1_data_V_ce0, "(port)csr1_data_V_ce0");
    sc_trace(mVcdFile, csr1_data_V_q0, "(port)csr1_data_V_q0");
    sc_trace(mVcdFile, csr2_rowptr_address0, "(port)csr2_rowptr_address0");
    sc_trace(mVcdFile, csr2_rowptr_ce0, "(port)csr2_rowptr_ce0");
    sc_trace(mVcdFile, csr2_rowptr_q0, "(port)csr2_rowptr_q0");
    sc_trace(mVcdFile, csr2_rowptr_address1, "(port)csr2_rowptr_address1");
    sc_trace(mVcdFile, csr2_rowptr_ce1, "(port)csr2_rowptr_ce1");
    sc_trace(mVcdFile, csr2_rowptr_q1, "(port)csr2_rowptr_q1");
    sc_trace(mVcdFile, csr2_colind_address0, "(port)csr2_colind_address0");
    sc_trace(mVcdFile, csr2_colind_ce0, "(port)csr2_colind_ce0");
    sc_trace(mVcdFile, csr2_colind_q0, "(port)csr2_colind_q0");
    sc_trace(mVcdFile, csr2_data_V_address0, "(port)csr2_data_V_address0");
    sc_trace(mVcdFile, csr2_data_V_ce0, "(port)csr2_data_V_ce0");
    sc_trace(mVcdFile, csr2_data_V_q0, "(port)csr2_data_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_3_fu_438_p2, "i_3_fu_438_p2");
    sc_trace(mVcdFile, i_3_reg_636, "i_3_reg_636");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_fu_432_p2, "exitcond_fu_432_p2");
    sc_trace(mVcdFile, tmp_s_fu_451_p1, "tmp_s_fu_451_p1");
    sc_trace(mVcdFile, tmp_s_reg_646, "tmp_s_reg_646");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, end_idx_1_reg_676, "end_idx_1_reg_676");
    sc_trace(mVcdFile, end_idx_2_reg_689, "end_idx_2_reg_689");
    sc_trace(mVcdFile, tmp_76_fu_473_p1, "tmp_76_fu_473_p1");
    sc_trace(mVcdFile, tmp_76_reg_705, "tmp_76_reg_705");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_75_fu_467_p2, "tmp_75_fu_467_p2");
    sc_trace(mVcdFile, tmp_77_fu_478_p1, "tmp_77_fu_478_p1");
    sc_trace(mVcdFile, tmp_77_reg_716, "tmp_77_reg_716");
    sc_trace(mVcdFile, z_idx_fu_501_p2, "z_idx_fu_501_p2");
    sc_trace(mVcdFile, z_idx_reg_727, "z_idx_reg_727");
    sc_trace(mVcdFile, csr1_colind_load_reg_733, "csr1_colind_load_reg_733");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_78_fu_512_p2, "tmp_78_fu_512_p2");
    sc_trace(mVcdFile, tmp_78_reg_738, "tmp_78_reg_738");
    sc_trace(mVcdFile, tmp_84_fu_524_p1, "tmp_84_fu_524_p1");
    sc_trace(mVcdFile, tmp_84_reg_745, "tmp_84_reg_745");
    sc_trace(mVcdFile, tmp_83_fu_518_p2, "tmp_83_fu_518_p2");
    sc_trace(mVcdFile, csr1_data_V_addr_gep_fu_172_p3, "csr1_data_V_addr_gep_fu_172_p3");
    sc_trace(mVcdFile, csr2_data_V_addr_gep_fu_180_p3, "csr2_data_V_addr_gep_fu_180_p3");
    sc_trace(mVcdFile, grp_fu_418_p2, "grp_fu_418_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_425_p2, "grp_fu_425_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_82_fu_529_p2, "tmp_82_fu_529_p2");
    sc_trace(mVcdFile, tmp_82_reg_782, "tmp_82_reg_782");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, indvars_iv_next_fu_541_p2, "indvars_iv_next_fu_541_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_85_fu_547_p2, "tmp_85_fu_547_p2");
    sc_trace(mVcdFile, j_6_fu_558_p2, "j_6_fu_558_p2");
    sc_trace(mVcdFile, j_6_reg_805, "j_6_reg_805");
    sc_trace(mVcdFile, z_idx_2_fu_582_p2, "z_idx_2_fu_582_p2");
    sc_trace(mVcdFile, z_idx_2_reg_810, "z_idx_2_reg_810");
    sc_trace(mVcdFile, z_idx_1_fu_593_p2, "z_idx_1_fu_593_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_91_fu_599_p2, "tmp_91_fu_599_p2");
    sc_trace(mVcdFile, k_5_fu_610_p2, "k_5_fu_610_p2");
    sc_trace(mVcdFile, k_5_reg_833, "k_5_reg_833");
    sc_trace(mVcdFile, z_idx_5_fu_627_p2, "z_idx_5_fu_627_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i_reg_308, "i_reg_308");
    sc_trace(mVcdFile, indvars_iv_reg_319, "indvars_iv_reg_319");
    sc_trace(mVcdFile, ap_phi_mux_j_2_phi_fu_353_p6, "ap_phi_mux_j_2_phi_fu_353_p6");
    sc_trace(mVcdFile, j6_reg_329, "j6_reg_329");
    sc_trace(mVcdFile, ap_phi_mux_k_2_phi_fu_367_p6, "ap_phi_mux_k_2_phi_fu_367_p6");
    sc_trace(mVcdFile, k1_reg_339, "k1_reg_339");
    sc_trace(mVcdFile, j_2_reg_349, "j_2_reg_349");
    sc_trace(mVcdFile, k_2_reg_363, "k_2_reg_363");
    sc_trace(mVcdFile, z_idx_3_reg_377, "z_idx_3_reg_377");
    sc_trace(mVcdFile, j_3_reg_388, "j_3_reg_388");
    sc_trace(mVcdFile, z_idx_4_reg_398, "z_idx_4_reg_398");
    sc_trace(mVcdFile, k_3_reg_408, "k_3_reg_408");
    sc_trace(mVcdFile, tmp_fu_444_p1, "tmp_fu_444_p1");
    sc_trace(mVcdFile, agg_result_data_V_ad_496_gep_fu_202_p3, "agg_result_data_V_ad_496_gep_fu_202_p3");
    sc_trace(mVcdFile, tmp_81_fu_535_p1, "tmp_81_fu_535_p1");
    sc_trace(mVcdFile, tmp_87_fu_552_p1, "tmp_87_fu_552_p1");
    sc_trace(mVcdFile, tmp_86_fu_587_p1, "tmp_86_fu_587_p1");
    sc_trace(mVcdFile, tmp_93_fu_604_p1, "tmp_93_fu_604_p1");
    sc_trace(mVcdFile, tmp_92_fu_616_p1, "tmp_92_fu_616_p1");
    sc_trace(mVcdFile, extLd8_fu_507_p1, "extLd8_fu_507_p1");
    sc_trace(mVcdFile, extLd_fu_622_p1, "extLd_fu_622_p1");
    sc_trace(mVcdFile, tmp_73_fu_457_p2, "tmp_73_fu_457_p2");
    sc_trace(mVcdFile, tmp_74_fu_462_p2, "tmp_74_fu_462_p2");
    sc_trace(mVcdFile, tmp_79_fu_483_p2, "tmp_79_fu_483_p2");
    sc_trace(mVcdFile, tmp_80_fu_495_p2, "tmp_80_fu_495_p2");
    sc_trace(mVcdFile, smax1_fu_488_p3, "smax1_fu_488_p3");
    sc_trace(mVcdFile, tmp_88_fu_564_p2, "tmp_88_fu_564_p2");
    sc_trace(mVcdFile, smax_fu_569_p3, "smax_fu_569_p3");
    sc_trace(mVcdFile, tmp_89_fu_576_p2, "tmp_89_fu_576_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

accumulate::~accumulate() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void accumulate::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_91_fu_599_p2.read()))) {
        i_reg_308 = i_3_reg_636.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_308 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvars_iv_reg_319 = agg_result_rowptr_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indvars_iv_reg_319 = indvars_iv_next_fu_541_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j6_reg_329 = csr1_rowptr_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        j6_reg_329 = ap_phi_mux_j_2_phi_fu_353_p6.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_2_reg_349 = j6_reg_329.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_reg_738.read())))) {
        j_2_reg_349 = grp_fu_425_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        j_3_reg_388 = j_6_reg_805.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_75_fu_467_p2.read()))) {
        j_3_reg_388 = j6_reg_329.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        k1_reg_339 = csr2_rowptr_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        k1_reg_339 = ap_phi_mux_k_2_phi_fu_367_p6.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        k_2_reg_363 = k1_reg_339.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_reg_738.read())))) {
        k_2_reg_363 = grp_fu_418_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        k_3_reg_408 = k_5_reg_833.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_85_fu_547_p2.read()))) {
        k_3_reg_408 = k1_reg_339.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        z_idx_3_reg_377 = z_idx_1_fu_593_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_75_fu_467_p2.read()))) {
        z_idx_3_reg_377 = indvars_iv_reg_319.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        z_idx_4_reg_398 = z_idx_5_fu_627_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_85_fu_547_p2.read()))) {
        z_idx_4_reg_398 = z_idx_reg_727.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        csr1_colind_load_reg_733 = csr1_colind_q0.read();
        tmp_78_reg_738 = tmp_78_fu_512_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        end_idx_1_reg_676 = csr1_rowptr_q1.read();
        end_idx_2_reg_689 = csr2_rowptr_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_3_reg_636 = i_3_fu_438_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_85_fu_547_p2.read()))) {
        j_6_reg_805 = j_6_fu_558_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_91_fu_599_p2.read()))) {
        k_5_reg_833 = k_5_fu_610_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_75_fu_467_p2.read(), ap_const_lv1_1))) {
        tmp_76_reg_705 = tmp_76_fu_473_p1.read();
        tmp_77_reg_716 = tmp_77_fu_478_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_82_reg_782 = tmp_82_fu_529_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()))) {
        tmp_84_reg_745 = tmp_84_fu_524_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_432_p2.read(), ap_const_lv1_0))) {
        tmp_s_reg_646 = tmp_s_fu_451_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_85_fu_547_p2.read()))) {
        z_idx_2_reg_810 = z_idx_2_fu_582_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_75_fu_467_p2.read()))) {
        z_idx_reg_727 = z_idx_fu_501_p2.read();
    }
}

void accumulate::thread_agg_result_colind_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        agg_result_colind_address0 =  (sc_lv<18>) (tmp_92_fu_616_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        agg_result_colind_address0 =  (sc_lv<18>) (tmp_86_fu_587_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        agg_result_colind_address0 =  (sc_lv<18>) (tmp_81_fu_535_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        agg_result_colind_address0 =  (sc_lv<18>) (tmp_84_reg_745.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        agg_result_colind_address0 =  (sc_lv<18>) (tmp_84_fu_524_p1.read());
    } else {
        agg_result_colind_address0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void accumulate::thread_agg_result_colind_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        agg_result_colind_ce0 = ap_const_logic_1;
    } else {
        agg_result_colind_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_agg_result_colind_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        agg_result_colind_d0 = extLd_fu_622_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        agg_result_colind_d0 = csr1_colind_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        agg_result_colind_d0 = csr1_colind_load_reg_733.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        agg_result_colind_d0 = extLd8_fu_507_p1.read();
    } else {
        agg_result_colind_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void accumulate::thread_agg_result_colind_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_83_fu_518_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_reg_738.read())))) {
        agg_result_colind_we0 = ap_const_logic_1;
    } else {
        agg_result_colind_we0 = ap_const_logic_0;
    }
}

void accumulate::thread_agg_result_data_V_ad_496_gep_fu_202_p3() {
    agg_result_data_V_ad_496_gep_fu_202_p3 =  (sc_lv<18>) (tmp_84_reg_745.read());
}

void accumulate::thread_agg_result_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        agg_result_data_V_address0 =  (sc_lv<18>) (tmp_92_fu_616_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        agg_result_data_V_address0 =  (sc_lv<18>) (tmp_86_fu_587_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        agg_result_data_V_address0 =  (sc_lv<18>) (tmp_81_fu_535_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        agg_result_data_V_address0 = agg_result_data_V_ad_496_gep_fu_202_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        agg_result_data_V_address0 =  (sc_lv<18>) (tmp_84_reg_745.read());
    } else {
        agg_result_data_V_address0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void accumulate::thread_agg_result_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        agg_result_data_V_ce0 = ap_const_logic_1;
    } else {
        agg_result_data_V_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_agg_result_data_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        agg_result_data_V_d0 = tmp_82_reg_782.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        agg_result_data_V_d0 = csr1_data_V_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        agg_result_data_V_d0 = csr2_data_V_q0.read();
    } else {
        agg_result_data_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void accumulate::thread_agg_result_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_reg_738.read())))) {
        agg_result_data_V_we0 = ap_const_logic_1;
    } else {
        agg_result_data_V_we0 = ap_const_logic_0;
    }
}

void accumulate::thread_agg_result_rowptr_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        agg_result_rowptr_address0 =  (sc_lv<9>) (tmp_s_reg_646.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        agg_result_rowptr_address0 =  (sc_lv<9>) (tmp_fu_444_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        agg_result_rowptr_address0 =  (sc_lv<9>) (ap_const_lv64_0);
    } else {
        agg_result_rowptr_address0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void accumulate::thread_agg_result_rowptr_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)))) {
        agg_result_rowptr_ce0 = ap_const_logic_1;
    } else {
        agg_result_rowptr_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_agg_result_rowptr_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        agg_result_rowptr_d0 = z_idx_2_reg_810.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        agg_result_rowptr_d0 = ap_const_lv32_0;
    } else {
        agg_result_rowptr_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void accumulate::thread_agg_result_rowptr_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_91_fu_599_p2.read())))) {
        agg_result_rowptr_we0 = ap_const_logic_1;
    } else {
        agg_result_rowptr_we0 = ap_const_logic_0;
    }
}

void accumulate::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void accumulate::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void accumulate::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void accumulate::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void accumulate::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void accumulate::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void accumulate::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void accumulate::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void accumulate::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void accumulate::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void accumulate::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void accumulate::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void accumulate::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void accumulate::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_432_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void accumulate::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void accumulate::thread_ap_phi_mux_j_2_phi_fu_353_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_reg_738.read()))) {
        ap_phi_mux_j_2_phi_fu_353_p6 = grp_fu_425_p2.read();
    } else {
        ap_phi_mux_j_2_phi_fu_353_p6 = j_2_reg_349.read();
    }
}

void accumulate::thread_ap_phi_mux_k_2_phi_fu_367_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_reg_738.read()))) {
        ap_phi_mux_k_2_phi_fu_367_p6 = grp_fu_418_p2.read();
    } else {
        ap_phi_mux_k_2_phi_fu_367_p6 = k_2_reg_363.read();
    }
}

void accumulate::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_432_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void accumulate::thread_csr1_colind_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        csr1_colind_address0 =  (sc_lv<18>) (tmp_87_fu_552_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        csr1_colind_address0 =  (sc_lv<18>) (tmp_76_fu_473_p1.read());
    } else {
        csr1_colind_address0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void accumulate::thread_csr1_colind_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        csr1_colind_ce0 = ap_const_logic_1;
    } else {
        csr1_colind_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_csr1_data_V_addr_gep_fu_172_p3() {
    csr1_data_V_addr_gep_fu_172_p3 =  (sc_lv<18>) (tmp_76_reg_705.read());
}

void accumulate::thread_csr1_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        csr1_data_V_address0 =  (sc_lv<18>) (tmp_87_fu_552_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_fu_512_p2.read()))) {
        csr1_data_V_address0 = csr1_data_V_addr_gep_fu_172_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_83_fu_518_p2.read()))) {
        csr1_data_V_address0 =  (sc_lv<18>) (tmp_76_reg_705.read());
    } else {
        csr1_data_V_address0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void accumulate::thread_csr1_data_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_83_fu_518_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_fu_512_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        csr1_data_V_ce0 = ap_const_logic_1;
    } else {
        csr1_data_V_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_csr1_rowptr_address0() {
    csr1_rowptr_address0 =  (sc_lv<9>) (tmp_fu_444_p1.read());
}

void accumulate::thread_csr1_rowptr_address1() {
    csr1_rowptr_address1 =  (sc_lv<9>) (tmp_s_fu_451_p1.read());
}

void accumulate::thread_csr1_rowptr_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        csr1_rowptr_ce0 = ap_const_logic_1;
    } else {
        csr1_rowptr_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_csr1_rowptr_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        csr1_rowptr_ce1 = ap_const_logic_1;
    } else {
        csr1_rowptr_ce1 = ap_const_logic_0;
    }
}

void accumulate::thread_csr2_colind_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        csr2_colind_address0 =  (sc_lv<18>) (tmp_93_fu_604_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        csr2_colind_address0 =  (sc_lv<18>) (tmp_77_fu_478_p1.read());
    } else {
        csr2_colind_address0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void accumulate::thread_csr2_colind_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        csr2_colind_ce0 = ap_const_logic_1;
    } else {
        csr2_colind_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_csr2_data_V_addr_gep_fu_180_p3() {
    csr2_data_V_addr_gep_fu_180_p3 =  (sc_lv<18>) (tmp_77_reg_716.read());
}

void accumulate::thread_csr2_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        csr2_data_V_address0 =  (sc_lv<18>) (tmp_93_fu_604_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_fu_512_p2.read()))) {
        csr2_data_V_address0 = csr2_data_V_addr_gep_fu_180_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_83_fu_518_p2.read()))) {
        csr2_data_V_address0 =  (sc_lv<18>) (tmp_77_reg_716.read());
    } else {
        csr2_data_V_address0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void accumulate::thread_csr2_data_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_83_fu_518_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_78_fu_512_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        csr2_data_V_ce0 = ap_const_logic_1;
    } else {
        csr2_data_V_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_csr2_rowptr_address0() {
    csr2_rowptr_address0 =  (sc_lv<9>) (tmp_fu_444_p1.read());
}

void accumulate::thread_csr2_rowptr_address1() {
    csr2_rowptr_address1 =  (sc_lv<9>) (tmp_s_fu_451_p1.read());
}

void accumulate::thread_csr2_rowptr_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        csr2_rowptr_ce0 = ap_const_logic_1;
    } else {
        csr2_rowptr_ce0 = ap_const_logic_0;
    }
}

void accumulate::thread_csr2_rowptr_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        csr2_rowptr_ce1 = ap_const_logic_1;
    } else {
        csr2_rowptr_ce1 = ap_const_logic_0;
    }
}

void accumulate::thread_exitcond_fu_432_p2() {
    exitcond_fu_432_p2 = (!i_reg_308.read().is_01() || !ap_const_lv9_1EE.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_308.read() == ap_const_lv9_1EE);
}

void accumulate::thread_extLd8_fu_507_p1() {
    extLd8_fu_507_p1 = esl_zext<32,9>(csr2_colind_q0.read());
}

void accumulate::thread_extLd_fu_622_p1() {
    extLd_fu_622_p1 = esl_zext<32,9>(csr2_colind_q0.read());
}

void accumulate::thread_grp_fu_418_p2() {
    grp_fu_418_p2 = (!k1_reg_339.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(k1_reg_339.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_grp_fu_425_p2() {
    grp_fu_425_p2 = (!j6_reg_329.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(j6_reg_329.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_i_3_fu_438_p2() {
    i_3_fu_438_p2 = (!i_reg_308.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_308.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void accumulate::thread_indvars_iv_next_fu_541_p2() {
    indvars_iv_next_fu_541_p2 = (!indvars_iv_reg_319.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(indvars_iv_reg_319.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_j_6_fu_558_p2() {
    j_6_fu_558_p2 = (!j_3_reg_388.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(j_3_reg_388.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_k_5_fu_610_p2() {
    k_5_fu_610_p2 = (!k_3_reg_408.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(k_3_reg_408.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_smax1_fu_488_p3() {
    smax1_fu_488_p3 = (!tmp_79_fu_483_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_79_fu_483_p2.read()[0].to_bool())? j6_reg_329.read(): end_idx_1_reg_676.read());
}

void accumulate::thread_smax_fu_569_p3() {
    smax_fu_569_p3 = (!tmp_88_fu_564_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_88_fu_564_p2.read()[0].to_bool())? k1_reg_339.read(): end_idx_2_reg_689.read());
}

void accumulate::thread_tmp_73_fu_457_p2() {
    tmp_73_fu_457_p2 = (!j6_reg_329.read().is_01() || !end_idx_1_reg_676.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j6_reg_329.read()) < sc_bigint<32>(end_idx_1_reg_676.read()));
}

void accumulate::thread_tmp_74_fu_462_p2() {
    tmp_74_fu_462_p2 = (!k1_reg_339.read().is_01() || !end_idx_2_reg_689.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k1_reg_339.read()) < sc_bigint<32>(end_idx_2_reg_689.read()));
}

void accumulate::thread_tmp_75_fu_467_p2() {
    tmp_75_fu_467_p2 = (tmp_73_fu_457_p2.read() & tmp_74_fu_462_p2.read());
}

void accumulate::thread_tmp_76_fu_473_p1() {
    tmp_76_fu_473_p1 = esl_sext<64,32>(j6_reg_329.read());
}

void accumulate::thread_tmp_77_fu_478_p1() {
    tmp_77_fu_478_p1 = esl_sext<64,32>(k1_reg_339.read());
}

void accumulate::thread_tmp_78_fu_512_p2() {
    tmp_78_fu_512_p2 = (!csr1_colind_q0.read().is_01() || !extLd8_fu_507_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(csr1_colind_q0.read() == extLd8_fu_507_p1.read());
}

void accumulate::thread_tmp_79_fu_483_p2() {
    tmp_79_fu_483_p2 = (!j6_reg_329.read().is_01() || !end_idx_1_reg_676.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j6_reg_329.read()) > sc_bigint<32>(end_idx_1_reg_676.read()));
}

void accumulate::thread_tmp_80_fu_495_p2() {
    tmp_80_fu_495_p2 = (!indvars_iv_reg_319.read().is_01() || !j6_reg_329.read().is_01())? sc_lv<32>(): (sc_bigint<32>(indvars_iv_reg_319.read()) - sc_bigint<32>(j6_reg_329.read()));
}

void accumulate::thread_tmp_81_fu_535_p1() {
    tmp_81_fu_535_p1 = esl_sext<64,32>(indvars_iv_reg_319.read());
}

void accumulate::thread_tmp_82_fu_529_p2() {
    tmp_82_fu_529_p2 = (!csr2_data_V_q0.read().is_01() || !csr1_data_V_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(csr2_data_V_q0.read()) + sc_biguint<32>(csr1_data_V_q0.read()));
}

void accumulate::thread_tmp_83_fu_518_p2() {
    tmp_83_fu_518_p2 = (!csr1_colind_q0.read().is_01() || !extLd8_fu_507_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(csr1_colind_q0.read()) < sc_bigint<32>(extLd8_fu_507_p1.read()));
}

void accumulate::thread_tmp_84_fu_524_p1() {
    tmp_84_fu_524_p1 = esl_sext<64,32>(indvars_iv_reg_319.read());
}

void accumulate::thread_tmp_85_fu_547_p2() {
    tmp_85_fu_547_p2 = (!j_3_reg_388.read().is_01() || !end_idx_1_reg_676.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_3_reg_388.read()) < sc_bigint<32>(end_idx_1_reg_676.read()));
}

void accumulate::thread_tmp_86_fu_587_p1() {
    tmp_86_fu_587_p1 = esl_sext<64,32>(z_idx_3_reg_377.read());
}

void accumulate::thread_tmp_87_fu_552_p1() {
    tmp_87_fu_552_p1 = esl_sext<64,32>(j_3_reg_388.read());
}

void accumulate::thread_tmp_88_fu_564_p2() {
    tmp_88_fu_564_p2 = (!k1_reg_339.read().is_01() || !end_idx_2_reg_689.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k1_reg_339.read()) > sc_bigint<32>(end_idx_2_reg_689.read()));
}

void accumulate::thread_tmp_89_fu_576_p2() {
    tmp_89_fu_576_p2 = (!smax_fu_569_p3.read().is_01() || !k1_reg_339.read().is_01())? sc_lv<32>(): (sc_biguint<32>(smax_fu_569_p3.read()) - sc_bigint<32>(k1_reg_339.read()));
}

void accumulate::thread_tmp_91_fu_599_p2() {
    tmp_91_fu_599_p2 = (!k_3_reg_408.read().is_01() || !end_idx_2_reg_689.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k_3_reg_408.read()) < sc_bigint<32>(end_idx_2_reg_689.read()));
}

void accumulate::thread_tmp_92_fu_616_p1() {
    tmp_92_fu_616_p1 = esl_sext<64,32>(z_idx_4_reg_398.read());
}

void accumulate::thread_tmp_93_fu_604_p1() {
    tmp_93_fu_604_p1 = esl_sext<64,32>(k_3_reg_408.read());
}

void accumulate::thread_tmp_fu_444_p1() {
    tmp_fu_444_p1 = esl_zext<64,9>(i_reg_308.read());
}

void accumulate::thread_tmp_s_fu_451_p1() {
    tmp_s_fu_451_p1 = esl_zext<64,9>(i_3_fu_438_p2.read());
}

void accumulate::thread_z_idx_1_fu_593_p2() {
    z_idx_1_fu_593_p2 = (!z_idx_3_reg_377.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(z_idx_3_reg_377.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_z_idx_2_fu_582_p2() {
    z_idx_2_fu_582_p2 = (!z_idx_reg_727.read().is_01() || !tmp_89_fu_576_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(z_idx_reg_727.read()) + sc_biguint<32>(tmp_89_fu_576_p2.read()));
}

void accumulate::thread_z_idx_5_fu_627_p2() {
    z_idx_5_fu_627_p2 = (!z_idx_4_reg_398.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(z_idx_4_reg_398.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void accumulate::thread_z_idx_fu_501_p2() {
    z_idx_fu_501_p2 = (!tmp_80_fu_495_p2.read().is_01() || !smax1_fu_488_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_80_fu_495_p2.read()) + sc_biguint<32>(smax1_fu_488_p3.read()));
}

void accumulate::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_432_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_75_fu_467_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_83_fu_518_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_78_fu_512_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_83_fu_518_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_85_fu_547_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_91_fu_599_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<13>) ("XXXXXXXXXXXXX");
            break;
    }
}

}

