// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mult_HH_
#define _mult_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct mult : public sc_module {
    // Port declarations 4
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > a_V;
    sc_in< sc_lv<32> > b_V;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    mult(sc_module_name name);
    SC_HAS_PROCESS(mult);

    ~mult();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<32> > r_V_fu_32_p0;
    sc_signal< sc_lv<32> > r_V_fu_32_p1;
    sc_signal< sc_lv<48> > r_V_fu_32_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_r_V_fu_32_p0();
    void thread_r_V_fu_32_p1();
    void thread_r_V_fu_32_p2();
};

}

using namespace ap_rtl;

#endif
